Д NEW96 ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД New-1997 Д
 Msg  : 70 of 70                             Addr             Date
 From : Ђ«ҐЄбҐ© ‚ ­ҐҐў                2:5003/15.1           26.06.96
 Subj : Џ ¤ ойЁ© ‘­ҐЈ
ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД

